name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: darodrig/devimage

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make test
